### ISSUE TITLE
MacOS make error

### ISSUE THREAD

**Issue by watkinsr** [akermu/emacs-libvterm#16]
[ 91%] Building C object CMakeFiles/vterm-module.dir/elisp.c.o
[100%] Linking C shared module ../vterm-module.so
ld: library not found for -lvterm

Any ideas?

- Ryan

**Comment by akermu** [comment]
You probably haven't installed libvterm.

**Comment by deb0ch** [comment]
Just built and tested with`make run` successfully on MacOS, just had to `brew install libvterm` in the process.

Maybe it's worth adding it to the Readme, while it might be obvious to you and me because we have experience with building projects I totally get that it is not to many people. I remember very well the days when it was not for me.

In any case, I think this issue can be closed.

**Comment by akermu** [comment]
Fixed in commit cad535b.
