### ISSUE TITLE
vterm-send-return crashing Emacs when not in vterm buffer

### ISSUE THREAD

**Issue by Linuus** [akermu/emacs-libvterm#245]
If I run `(vterm-send-return)` when I'm not in a vterm buffer my entire Emacs crashes. It would be nice with an error message instead :)

I guess we need to check the variable `vterm--term`.

**Comment by Sbozzolo** [comment]
Thanks for your bug report. Emacs crashes because of the line `(vterm--get-icrnl vterm--term)`. When `vterm--term` is nil, the C function `Fvterm_get_icrnl` doesn't know what to do. In the future, it may be useful to make sure that the low-level C primitives know how to handle this kind of scenarios so that packages/configurations built on top of `vterm` don't have to worry about providing valid input. For the moment, I will patch the elisp code.
