### ISSUE TITLE
run a function when switching to vterm

### ISSUE THREAD

**Issue by divansantana** [akermu/emacs-libvterm#329]
Hi,

```
(add-hook 'vterm-mode-hook  'xah-fly-insert-mode-activate)
```

I thought that the above would run `xah-fly-insert-mode-activate` upon switching from a buffer to the vterm buffer.

It seems the above hook only triggers when launching vterm for the first time.

Is there a way to run a function when switching to vterm?

**Comment by Sbozzolo** [comment]
This looks like a general Emacs question: you want to run a function every time you visit a buffer that has a specific major mode (in this case, vterm). I recommend you open an issue in the [xah lee keys repo](https://github.com/xahlee/xah-fly-keys/issues) because there may be an idiomatic way to achieve what you want.

**Comment by divansantana** [comment]
@Sbozzolo Thanks for the quick reply. I understand. I figured out a way to do it. With the function switch-to-vterm I wrote, I simply call the xah-fly-insert-mode-activate function too.
