### ISSUE TITLE
man page pollute the display of buffer

### ISSUE THREAD

**Issue by QiangF** [akermu/emacs-libvterm#37]
To reproduce:
1 start a new vterm buffer
2 man ls
3 quit the man page, the screen is only partially updated.

**Comment by deb0ch** [comment]
I just tried and don't reproduce with the steps you provided.

Can you please provide more details about the bug and how to reproduce it ? What is your system ? It would be great if you could also add screenshots, because we don't know exactly what `the screen is only partially updated` means, and it would be helpful 🤔 Do you reproduce in `emacs -Q`, or if not, what would be a minimal configuration `emacs -Q -l minimum_configuration_file.el` to reproduce ?

Thanks in advance 😁

**Comment by akermu** [comment]
I can reproduce this behavior when using `bash'. With `zsh' it works.

**Comment by QiangF** [comment]
Thank you! I will try zsh.

**Comment by akermu** [comment]
Something fixed it on my system and I don't know what. The problem is as far as I can tell, that these lines shouldn't be deleted but the prompt should at the bottom. @QiangF Can you still reproduce it with `bash`?

**Comment by QiangF** [comment]
Yes, with the newest code I can still reproduce this. We need a way to make the prompt at the bottom.

**Comment by deadtrickster** [comment]
same with htop for me

**Comment by akermu** [comment]
@QiangF @deadtrickster ec95898 should fix this, can you verify this?

**Comment by akermu** [comment]
@deadtrickster I can not reproduce the background glitches on my end, can you give me a minimal example, how to reproduce this under `emacs -Q`?
