### ISSUE TITLE
Publish to Melpa

### ISSUE THREAD

**Issue by deb0ch** [akermu/emacs-libvterm#53]
Are there any plans to publish `emacs-libvterm` to Melpa ?

If not I think there should be. This project has reached a great level of usability, and Melpa will greatly help making it available. Particularly for Spacemacs, which heavily relies on it for dependencies.

If you want Elpa why not, I think it was your intention in #1 a year ago, but as time passes and contributors add up it will be harder and harder to get their signature. It is also a risk for the future of this project, as having to sign papers _will_ deter a range of future contributors, holding back the project like it held back the Emacs project for 40 years (in my opinion). I wouldn't be against signing them though, for what it's worth.

I'm sure that publishing to Melpa now is compatible with publishing to Elpa later.

Publishing is quite simple, you just need to fix your headers with relevant info (sometimes they even do it and send the PR to your project themselves) and send a pull request to the Melpa project on GitHub with a fetching recipe.

I can take care of it no problem since I've already done it for https://github.com/deb0ch/emacs-winum. I would just feel awkward doing it without your agreement, @akermu, so please tell me what you think 😁

**Comment by knazarov** [comment]
The problem is actually that emacs-libvterm has a compiled extension, which complicates things a bit.
I researched this, but was unable to find any information on how to run user-defined make scripts during package build. If anyone has any pointers how to do it, I'd be glad to help.

On top of that, libvterm probably should be included either as a submodule or just plain-old copied inside emacs-libvterm source tree. Otherwise it won't be as out-of-the-box as other useful packages.

**Comment by aaronjensen** [comment]
pdf-tools compiles on install form melpa, not sure if that helps: https://github.com/politza/pdf-tools

**Comment by knazarov** [comment]
@aaronjensen thanks!

Looks like Melpa doesn't have a mechanism to distribute binary packages, so pdf-tools had invent its own. It turns out they check if the shared library is available, and if not, build it. It usually happens on first start.

Here's the relevant file:
https://github.com/politza/pdf-tools/blob/master/lisp/pdf-tools.el

**Comment by deb0ch** [comment]
@aaronjensen I had the same example in mind 😄 I took a look at it when I was working on this package install function and their system is a bit more complicated. I'm not sure, if we were to copy it, which parts of it are useful for what. Either way, it would require a bit of work.

@knazarov the fact that everything does not automagically install/compile is not a blocking problem for publishing on Melpa. Countless packages there have external dependencies as well, not automagically installed, with install instructions in their readme. Shipping `emacs-libvterm` with `libvterm` is already a work in progress (on the `vendor-libvterm` branch), and compiling the module is already automated and documented.

All that could be made better indeed, but it secondary and can be taken care of at a later time.

Right now the package is ready to be published and doing so would bring value.

**Comment by knazarov** [comment]
@deb0ch here's my take on vendoring libvterm: 
https://github.com/knazarov/emacs-libvterm/tree/vendor-libvterm

I skipped the libvterm build system to evade the trouble of marrying it with CMake and instead did everything in the parent CMakeLists.txt. libvterm itself is a submodule.

**Comment by deb0ch** [comment]
@knazarov I haven't taken a look at Akremu's branch but will take a look at both of yours whenever I have time (I'm on a road trip) 😁 I like using submodules because they are nice, don't bloat your repo and are linked to a specific commit. I'm just not sure if Melpa's fetcher supports them, if yes it would be great.

@TheBB thank you that's a very helpful insight !
It makes me think that so many packages either already have their own dependency installing system, or just lack one. Would it make sense to have a dependency installer as a separate project, that would cover all those use cases, and make those packages adopt it ? Every package implementing its own separate solution would be simpler at very short term, but I feel like we could make something better that could move the entire ecosystem forward.

I've been thinking of making such a thing for a long time now, after having had to read so many readmes and installing so many dependencies every time I added a layer to my Spacemacs, but without a good enough vision, or time on my hands, or a good occasion to actually get started. For starters, would it make more sense as a dependency, like Dash, in a separate GitHub repo, or as a feature to PR to Melpa or some other project ?

**Comment by TheBB** [comment]
I think the following initiatives would be useful:

1. A package with logic for fetching external dependencies (outside Emacs) on a suitably wide range of systems, which can also perhaps be configured in a once-and-for-all way for systems with a choice of package managers (homebrew, chocolatey, etc.)

2. A package with logic for *building* compiled components on a suitably wide range of systems. May or may not be bundled together with (1) as a single unit.

3. A discussion with MELPA and emacs-devel about how best to extend the package system with architecture information so that it can be used to distribute compiled components, rendering at least (2) obsolete to some degree. When this is decided, it would be possible to work this into the MELPA build process.

**Comment by TheBB** [comment]
Of course it's possible to put libvterm on MELPA without any of the above as already discussed.

**Comment by knazarov** [comment]
@deb0ch yes, melpa supports submodules.

As for packaging in general, I believe the decision to not support package versioning, dependencies and any build scripts was deliberate on the melpa part. These are really hard problems to solve.

And maybe we don't even need that much flexibility as in PyPi or npm. Just installing packages from public git repos from specific tags will be significantly better than what we have right now. Lua has a decent package manager called Luarocks, which I highly recommend everyone to check out to see what can be done with relatively little effort.

**Comment by eubarbosa** [comment]
ITS HAPPENING!

**Comment by deb0ch** [comment]
We are straying further and further from the original subject, let's open a separate issue for discussing the best way for automating the installation.

This thread is just for asking @akermu's blessing for publishing on Melpa, so, @akermu, what do you say ?

**Comment by deb0ch** [comment]
Yes, will do whenever I have time 👌✨

**Comment by jixiuf** [comment]
now emacs-libvterm is published in melpa
but Installing it from MELPA results in
>Compiling file /home/manuel/.emacs.d/elpa/vterm-20190502.1700/vterm.el at Sun May 12 10:23:06 2019
Entering directory ‘/home/manuel/.emacs.d/elpa/vterm-20190502.1700/’
vterm.el:77:1:Error: Cannot open load file: No such file or directory, vterm-module

https://github.com/melpa/melpa/pull/6133#issuecomment-491575617
so should we try to compile vterm-module after require `vterm-module` failed like this:

```
(unless (require 'vterm-module nil t)
  (vterm-module-compile)
  (require 'vterm-module))


```

**Comment by akermu** [comment]
`vterm` is now on `melpa`.
