### ISSUE TITLE
Bright colours not used on bold text

### ISSUE THREAD

**Issue by Artefact2** [akermu/emacs-libvterm#549]
Setting the foreground colour on bold text uses the 8-15 (bright) colours, but not in emacs vterm. Here is a comparison with xterm (below):

![emacs](https://user-images.githubusercontent.com/90720/134683377-04f147ae-2a15-44cb-a80b-66380f856aa7.png)
![xterm](https://user-images.githubusercontent.com/90720/134683394-42a922fe-50e5-4dae-8b93-d7eea6bb9738.png)

**Comment by ioreshnikov** [comment]
This seems to be quite a common behaviour among terminal emulators. See this discussion in `vim` repo for more examples:

https://github.com/vim/vim/issues/5929

IMHO, vterm should have an option to do that as well. For me personally it has been a source of confusion before:

https://github.com/akermu/emacs-libvterm/issues/481

**Comment by jixiuf** [comment]
Can you try this pr with 
(setq vterm-set-bold-hightbright  t)

**Comment by ioreshnikov** [comment]
So fast!

I tried it and it works as intendend. Screenshot below. Left is emacs, right is gnome-terminal.

![Снимок экрана от 2021-12-08 19-21-26](https://user-images.githubusercontent.com/1098912/145262636-992797ad-a8ed-4005-9f0e-36de206f8a06.png)

Except for the background color (which is due to `solaire-mode`) the colors look identical.

Thanks!
