### ISSUE TITLE
Mouse events such as scroll or click crash emacs when vterm is displaying.

### ISSUE THREAD

**Issue by rakanalh** [akermu/emacs-libvterm#6]
Launch vterm, start tmux and try to scroll using the mouse.
Or when you launch vterm, the scratch buffer is shown, click on it and back on the vterm buffer.

Both cases will crash emacs.

**Comment by rakanalh** [comment]
I was able to reproduce this on both MacOs & Linux and Emacs 25.1, 25.2.
Use case: 
1) Start emacs -Q
2) Scratch buffer is displayed
3) M-x vterm-create
4) Click the scratch buffer
5) Click back on the vterm buffer
Sigfault.

The error takes place here: https://github.com/akermu/emacs-libvterm/blob/master/vterm-module.c#L436
which is because `term` is NULL. digging a bit further i was able to figure out that it's caused by the second thread which constantly performs a `kill` call with SIGUSR1. Commenting that out leads to the sigfault not taking place. Furthermore, I added
```
(with-current-buffer buffer
              (message (buffer-name buffer)) <-- ADDED
              (unless (vterm-update vterm-term)
                (insert "\nProcess exited!\n\n"))))
```
To vterm_event func and the following is printed:
```
progn: Wrong type argument: user-ptrp, nil
```

I am not sure why the usrptr is NULL here so i'll keep digging.

**Comment by akermu** [comment]
Thanks for the detailed report! With your information I figured the culprit is in `vterm-self-insert`. This function gets called on every event in the vterm-buffer. It assumes the current buffer is a vterm-buffer, which is not the case with mouse events. As a quick workaround you can put

```elisp
(define-key vterm-mode-map [mouse-1] nil)
(define-key vterm-mode-map [mouse-2] nil)
(define-key vterm-mode-map [mouse-3] nil)
(define-key vterm-mode-map [mouse-4] nil)
(define-key vterm-mode-map [mouse-5] nil)
```
after ```(define-key vterm-mode-map [t] #'vterm-self-insert)``` [here](https://github.com/akermu/emacs-libvterm/blob/163dd21/vterm.el#L38).

I'll have to think about handling events better, the catch all clause seems not to be the right approach.

**Comment by rakanalh** [comment]
Thank you for looking into this. However, adding the define keys starting line 39 didn't solve the issue.
