### ISSUE TITLE
Unable to close vterm

### ISSUE THREAD

**Issue by theottm** [akermu/emacs-libvterm#607]
Hi,

whenever I try to kill a `vterm` buffer using `C-d` or `kill-this-buffer` I get the error:
> Attempt to delete minibuffer or sole ordinary window

The variable `vterm-kill-buffer-on-exit` is set to `t`. `vterm-exit-function` is also `nil`.

I'm running Emacs as a daemon and my WM is EXWM, but running as another process.

I just tried to split the window and then killing the vterm buffer works. So it seems killing a `vterm` also calls `delete-window`. Is there a way to avoid that?

**Comment by Sbozzolo** [comment]
My first guess is you have some other hooks/customization in place that conflict with vterm. Since you can easily reproduce the problem, my suggestion is bisecting your config file to find what is the problem. If the error happens even with a clean config, we can try to understand better what is going on.

**Comment by theottm** [comment]
Sounds like a good debugging strategy, thanks. I'll try that out.

**Comment by theottm** [comment]
It turns out this was caused by `vterm-toggle`. Setting `vterm-toggle-reset-window-configration-after-exit` to `t` fixed the problem.
