### ISSUE TITLE
Shell with ssh doesn't send the arrow keys and tab

### ISSUE THREAD

**Issue by mpedramfar** [akermu/emacs-libvterm#654]
As mentioned in https://github.com/akermu/emacs-libvterm/issues/567#issuecomment-1034717314, when a shell is opened over tramp, the arrow keys are not sent properly, neither is tab.
When I open a buffer over ssh and open vterm, pressing arrow keys inserts things like `^[[A` and pressing tab doesn't complete the commands, it insets a tab instead.

**Comment by mpedramfar** [comment]
I didn't realize at the time, but this was not a bug, just unexpected defaults. It was just running a `dash` shell for some reason.

**Comment by Bawaw** [comment]
I have the same problem. Did you figure what config is leading to it running `/bin/dash` instead of `/bin/bash` when opening a shell over tramp? 

On my end emacs `vterm-shell` is giving `/bin/bash` and `echo $Shell` in terminal also yields `/bin/bash` so I'm not sure why it is running dash instead of bash.
